replicaCount: 1

image:
  repository: ""   # e.g. tinorodney/avidlearner
  tag: ""          # e.g. latest/SHA
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

# Ingress host is "<release-name>.<domain>" for each domain listed here.
domains:
  - atarnet.org
  - alfaneti.uk

resources: {}
