replicaCount: 1

image:
  repository: ""   # e.g. tinorodney/avidlearner
  tag: ""          # e.g. latest/SHA
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  # host defaults to "<release>.atarnet.org" if not provided
  hosts:
    - host: ""      # optional; leave blank to auto-generate
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: tls-atarnet
      hosts:
        - ""        # optional; leave blank to auto-generate

resources: {}
