{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "nginx" }}
  rules:
    - host: {{ .Values.ingress.hosts | default (list (dict "host" (printf "%s.atarnet.org" .Release.Name))) | first | get "host" | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}
                port:
                  number: {{ .Values.service.port | default 80 }}
  tls:
    - secretName: {{ (index .Values.ingress.tls 0).secretName | default "tls-atarnet" }}
      hosts:
        - {{ .Values.ingress.hosts | default (list (dict "host" (printf "%s.atarnet.org" .Release.Name))) | first | get "host" | quote }}
{{- end }}
